PWD := $(shell pwd)
obj-m += spi_bcm-2835old-s.o

all:
	make ARCH=arm CROSS_COMPILE=$(TOOL_PATH)/$(CROSS_COMPILE) -C $(LINUX_SRC) SUBDIRS=$(PWD) modules
clean:
	rm -rf *.ko *.o *.symvers *.order *.mod.c *.mod.o
